# TCL File Generated by Component Editor 18.0
# Wed Oct 10 17:24:24 BRT 2018
# DO NOT MODIFY


# 
# keypad "keypad" v0.1
#  2018.10.10.17:24:24
# periferico para controlar keypad matricial de 12 teclas
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module keypad
# 
set_module_property DESCRIPTION "periferico para controlar keypad matricial de 12 teclas"
set_module_property NAME keypad
set_module_property VERSION 0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME keypad
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL keypad
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file keypad.vhd VHDL PATH IP/keypad.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL keypad
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file keypad.vhd VHDL PATH IP/keypad.vhd


# 
# parameters
# 
add_parameter LEN_ROW NATURAL 4
set_parameter_property LEN_ROW DEFAULT_VALUE 4
set_parameter_property LEN_ROW DISPLAY_NAME LEN_ROW
set_parameter_property LEN_ROW TYPE NATURAL
set_parameter_property LEN_ROW UNITS None
set_parameter_property LEN_ROW ALLOWED_RANGES 0:2147483647
set_parameter_property LEN_ROW HDL_PARAMETER true
add_parameter LEN_COL NATURAL 3
set_parameter_property LEN_COL DEFAULT_VALUE 3
set_parameter_property LEN_COL DISPLAY_NAME LEN_COL
set_parameter_property LEN_COL TYPE NATURAL
set_parameter_property LEN_COL UNITS None
set_parameter_property LEN_COL ALLOWED_RANGES 0:2147483647
set_parameter_property LEN_COL HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_address address Input 4
add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point row
# 
add_interface row conduit end
set_interface_property row associatedClock clock
set_interface_property row associatedReset ""
set_interface_property row ENABLED true
set_interface_property row EXPORT_OF ""
set_interface_property row PORT_NAME_MAP ""
set_interface_property row CMSIS_SVD_VARIABLES ""
set_interface_property row SVD_ADDRESS_GROUP ""

add_interface_port row Row in Output len_row


# 
# connection point col
# 
add_interface col conduit end
set_interface_property col associatedClock clock
set_interface_property col associatedReset ""
set_interface_property col ENABLED true
set_interface_property col EXPORT_OF ""
set_interface_property col PORT_NAME_MAP ""
set_interface_property col CMSIS_SVD_VARIABLES ""
set_interface_property col SVD_ADDRESS_GROUP ""

add_interface_port col Col out Input len_col


# 
# connection point led
# 
add_interface led conduit end
set_interface_property led associatedClock clock
set_interface_property led associatedReset ""
set_interface_property led ENABLED true
set_interface_property led EXPORT_OF ""
set_interface_property led PORT_NAME_MAP ""
set_interface_property led CMSIS_SVD_VARIABLES ""
set_interface_property led SVD_ADDRESS_GROUP ""

add_interface_port led led out Output 6


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1

